### ISSUE TITLE
Links in rss feed not working

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/geocat#155]
https://www.geocat.ch/geonetwork/srv/ger/rss.search
Links return an error (due to double back slash in URL)

**Comment by cmangeat** [comment]
https://github.com/geoadmin/geocat/commit/12df793469d4275d00ed6b61c0baeec77d2c1d45

https://github.com/geoadmin/geocat/commit/a38d7ba000a6aa00a59bcea2a76c3b1345ed1f57

https://github.com/geoadmin/geocat/commit/223a99caa88ebaf3d180c4764238238a217fc83c

to be deployed.
