### ISSUE TITLE
Question: API capabilities

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/geocat#34]
I am looking for some documentation about the GeoCat API capabilities.

Is there such a thing? Where could I find it?

Thanks in advance.

**Comment by ebelo** [comment]
Hi Loic, we don't use github issues, but jira.swisstopo.ch for the geocat project. Could you please record your questions/remarks in the jira software?

**Comment by loicgasser** [comment]
Hi sure I don't have access to it yet. But yes no problem.
