### ISSUE TITLE
50x errors on geocat instances

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/geocat#45]
https://logs.bgdi.ch/kibana/#/dashboard/elasticsearch/geocat%20errors%2050x

We can observe several 50x errors on the geocat instance. 

1. Some seem related to dedicated csw services for ASTRA and BAFUSe. 
2. Some are related to monitoring systems

Could you please analyze these issues ?

**Comment by ebelo** [comment]
Thanks for reporting. Issue migrated to Swisstopo Jira under the issue GEOCAT_SB-532 assigned to current sprint as we don't use the GitHub issues. Best regards
